swagger: "2.0"

info:
  description: "This is a powerfull API which allow to calculate the cost of the trip"
  version: "1.0"
  title: "LaDificil"
  contact:
    email: "fulldevs0@gmail.com"
  host: "https://dazzling-noether-69888d.netlify.app/"
  schemes: ["http"]

basePath: "/api/"

paths:
  /api/vehicle/:
    get:
      summary: "Will get the list of vehicles"
      description:
        "Will get the list of vehicles how contains his owns categories and features of the car"
      produces:
        - "application/json"
      responses:
        200:
          description: OK

    post:
      summary: "añade un pago a un inmueble especificado por el id del inmueble y el documento de identidad solo se puede pagar en dias impares"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "body"
          in: "body"
          description: "ID of contact to be deleted"
          required: true
          type: "string"
          schema:
            $ref: "#/definitions/Pago"
      responses:
        200:
          description: OK
        500:
          description: "Server Error"


definitions:
  Pago:
    type: "object"
    required:
    - "name"
    properties:
      fechaPago:
        type: date
        example: "04/07/2008"
        description: "debe ser un dia inpar"
      documentoIdentificacionArrendatario:
        type: integer
        example: 1254872552
      codigoInmueble:
        type: "string"
        example: "8872"
      valorPagado:
        type: integer
        example: 1000000
        description: "valor cancelado de el arrendamiento"
    xml:
      name: "Pago"
